image: python:3.6

pipelines:
  default:
      - step:
          script:
            - pip install -U tox
            - tox -e py36
  branches:
    master:
      - step:
          image: python:2.7
          script:
            - pip install -U tox
            - tox -e py27
      - step:
          script:
            - pip install -U tox
            - tox -e py36
      - step:
          image: pypy:latest
          script:
            - pip install -U tox
            - tox -e pypy
