image: python:latest

pipelines:
  default:
      - step:
          name: Python 2.7 Tests
          image: python:2.7
          script:
            - pip install -U tox
            - tox -e py27
          caches:
            - pip
      - step:
          name: Python 3.8 Tests
          image: python:3.8
          script:
            - pip install -U tox
            - tox -e py38
          caches:
            - pip
      - step:
          name: Pypy 3 Tests
          image: pypy:3
          script:
            - pip install -U tox
            - tox -e pypy3
          caches:
            - pip
  branches:
    master:
      - step:
          name: Python 2.7 Tests
          image: python:2.7
          script:
            - pip install -U tox
            - tox -e py27
          caches:
            - pip
      - step:
          name: Python 3.4 Tests
          image: python:3.4
          script:
            - pip install -U tox
            - tox -e py34
          caches:
            - pip
      - step:
          name: Python 3.5 Tests
          image: python:3.5
          script:
            - pip install -U tox
            - tox -e py35
          caches:
            - pip
      - step:
          name: Python 3.6 Tests
          image: python:3.6
          script:
            - pip install -U tox
            - tox -e py36
          caches:
            - pip
      - step:
          name: Python 3.7 Tests
          image: python:3.7
          script:
            - pip install -U tox
            - tox -e py37
          caches:
            - pip
      - step:
          name: Python 3.8 Tests
          image: python:3.8
          script:
            - pip install -U tox
            - tox -e py38
          caches:
            - pip
      - step:
          name: Pypy 3 Tests
          image: pypy:3
          script:
            - pip install -U tox
            - tox -e pypy3
          caches:
            - pip
      - step:
          name: Documentation
          script:
            - pip install -U tox
            - tox -e docs
          caches:
            - pip
      - step:
          name: Deploy To PyPi
          script:
            - bash -e deploy.bash
