image: python:latest

pipelines:
  default:
      - step: &py38
          name: Python 3.8 Tests
          image: python:3.8
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run python -m unittest discover tests/
          caches:
            - pip
      - step: &py39
          name: Python 3.9 Tests
          image: python:3.9
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run python -m unittest discover tests/
          caches:
            - pip
      - step: &py310
          name: Python 3.10 Tests
          image: python:3.10
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run python -m unittest discover tests/
          caches:
            - pip
      - step: &py311
          name: Python 3.11 Tests
          image: python:3.11
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run python -m unittest discover tests/
          caches:
            - pip
      - step: &pypy3
          name: Pypy 3 Tests
          image: pypy:3
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run python -m unittest discover tests/
          caches:
            - pip
  branches:
    release/*:
      - step:
          name: Lint using Flake8
          script:
            - pip install poetry
            - poetry install --with dev
            - poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude docs
            - poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude docs
          caches:
            - pip
      - step: *py38
      - step: *py39
      - step: *py310
      - step: *py311
      - step: *pypy3
      - step:
          name: Build Documentation
          script:
            - python -m pip install Sphinx
            - sphinx-build -b html docs/source/ docs/build/html/
          caches:
            - pip
      - step:
          name: Deploy To Test PyPi
          trigger: manual
          script:
            - pip install poetry
            - poetry config repositories.test-pypi https://test.pypi.org/legacy/
            - poetry publish --build --repository test-pypi --username __token__ --password ${TEST_PYPI_PASSWORD}
          caches:
            - pip
    master:
      - step: *py38
      - step: *py39
      - step: *py310
      - step: *py311
      - step: *pypy3
      - step:
          name: Deploy To PyPi
          script:
            - pip install poetry
            - poetry publish --build --username __token__ --password ${PYPI_PASSWORD}
          caches:
            - pip
