image: python:3.6

pipelines:
  default:
      - step:
          name: Python 2 Tests
          image: python:2.7
          script:
            - pip install -U tox
            - tox -e py27
          caches:
            - pip
      - step:
          name: Pypy Tests
          image: pypy:3
          script:
            - pip install -U tox
            - tox -e pypy3
          caches:
            - pip
      - step:
          name: Python3 Tests
          script:
            - pip install -U tox
            - tox -e py36
          caches:
            - pip
  branches:
    master:
      - step:
          name: Python 2 Tests
          image: python:2.7
          script:
            - pip install -U tox
            - tox -e py27
          caches:
            - pip
      - step:
          name: Pypy Tests
          image: pypy:latest
          script:
            - pip install -U tox
            - tox -e pypy
          caches:
            - pip
      - step:
          name: Python3 Tests
          script:
            - pip install -U tox
            - tox -e py36
          caches:
            - pip
      - step:
          name: Documentation
          script:
            - pip install -U tox
            - tox -e docs
          caches:
            - pip
      - step:
          name: Deploy To PyPi
          script:
            - bash -e deploy.bash
