name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install UV
      run: |
        pip install uv
    - name: Publish to PyPI
      run: |
        uv build && uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}