name: Publish to Test PyPI

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install UV
      run: |
        pip install uv
    - name: Publish to Test PyPI
      run: |
        uv build && uv publish --index test-pypi --username __token__ --password ${{ secrets.TEST_PYPI_API_TOKEN }}